// use aiken/cbor.{serialise}
// use aiken/collection/dict
// use aiken/collection/list
// use aiken/crypto.{VerificationKeyHash, sha2_256}
// use cardano/assets.{PolicyId, tokens}
// use cardano/transaction.{Input, OutputReference, Transaction}
// use utils

// validator (owner: VerificationKeyHash){
//     mint(_redeemer: Data, policy_id: PolicyId, self: Transaction) {
//         False 
//     }
// }
